services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DsTrinityDataBundle\Registry\ProxyResolverRegistryInterface: '@DsTrinityDataBundle\Registry\ProxyResolverRegistry'
    DsTrinityDataBundle\Registry\ProxyResolverRegistry: ~

    DsTrinityDataBundle\Resource\ProxyResolver\ObjectProxyResolver:
        tags:
            - {name: ds_trinity_data.proxy_resolver, identifier: default, type: object }
