services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DsTrinityDataBundle\Normalizer\ResourceNormalizer:
        tags:
            - { name: dynamic_search.resource_normalizer, identifier: trinity_resource_normalizer, data_provider: trinity_data }