services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DsTrinityDataBundle\Resource\Scaffolder\TrinityDataScaffolder:
        tags:
            - { name: dynamic_search.resource.scaffolder, priority: 10, identifier: trinity_data, data_provider: trinity_data }

    DsTrinityDataBundle\Resource\FieldTransformer\ElementIdExtractor:
        tags:
            - { name: dynamic_search.resource.field_transformer, identifier: element_id_extractor, resource_scaffolder: trinity_data }

    DsTrinityDataBundle\Resource\FieldTransformer\ObjectGetterExtractor:
        tags:
            - { name: dynamic_search.resource.field_transformer, identifier: object_getter_extractor, resource_scaffolder: trinity_data }

    DsTrinityDataBundle\Resource\FieldTransformer\ObjectLocalizedGetterExtractor:
        tags:
            - { name: dynamic_search.resource.field_transformer, identifier: object_localized_getter_extractor, resource_scaffolder: trinity_data }
